const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const {mkdirSync}=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
 const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','47291','--strictPort'],{stdio:'pipe'});
 let browser;
 try{
  await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Vite startup timeout')),10000);server.stdout.on('data',d=>{if(d.toString().includes('Local:')){clearTimeout(timeout);resolve()}});server.on('error',reject);server.on('exit',code=>{if(code)reject(new Error('Vite exited '+code))})});
  browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-webgl']});
  const page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('503 (Service Unavailable)'))errors.push(m.text())});
  await page.route('https://tiles.openfreemap.org/**',r=>r.fulfill({status:503,body:'offline fixture'}));
  await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:''}));
  await page.route('https://fonts.gstatic.com/**',r=>r.fulfill({body:''}));
  mkdirSync('.test-artifacts',{recursive:true});
  await page.goto('http://127.0.0.1:47291');
  await page.route('https://photon.komoot.io/api/**',r=>r.fulfill({json:{features:[{properties:{housenumber:'200',street:'King Street West',city:'Kitchener',country:'Canada'},geometry:{coordinates:[-80.4921882,43.4516223]}}]}}));
  await page.setViewportSize({width:390,height:844});
  await page.locator('#btn-new').click();
  assert.ok((await page.locator('#modal-body').innerText()).includes('Where’s your couch?'));
  await page.screenshot({path:'.test-artifacts/couch-setup.png'});
  await page.locator('input[name=q]').fill('200 King Street West Kitchener');
  await page.locator('#search-form button').click();
  await page.locator('#search-results button').waitFor();
  assert.ok((await page.locator('#search-results').innerText()).includes('200 King Street West'));
  await page.locator('#search-results button').click();
  await page.waitForFunction(()=>window.hoverghini.world&&!window.hoverghini.loading);
  const home=await page.evaluate(()=>window.hoverghini.save.safehouse);
  assert.equal(home.lat,43.4516223);assert.equal(home.lon,-80.4921882);
  assert.equal(await page.evaluate(()=>window.hoverghini.player.mode),'free');
  await page.evaluate(()=>window.hoverghini.openModal('holdings'));
  assert.ok((await page.locator('#modal-body').innerText()).includes('Starter safehouse'));
  await page.evaluate(()=>window.hoverghini.warp('Elsewhere',43.65,-79.38));
  assert.deepEqual(await page.evaluate(()=>window.hoverghini.save.safehouse),home);
  await page.reload();
  assert.deepEqual(await page.evaluate(()=>window.hoverghini.save.safehouse),home);
  await page.locator('#btn-continue').click();
  await page.waitForFunction(()=>window.hoverghini.world&&!window.hoverghini.loading);
  await page.evaluate(()=>window.hoverghini.openModal('holdings'));
  await page.locator('[data-act=home]').click();
  await page.waitForFunction(()=>!window.hoverghini.loading&&window.hoverghini.save.city.lat===43.4516223);
  assert.equal(await page.evaluate(()=>window.hoverghini.dealers.dealers.length),4);
  await page.evaluate(()=>{const g=window.hoverghini;g.player.speed=0;g.player.vel.set(0,0);g.save.money=150;g.stash()});
  assert.equal(await page.evaluate(()=>window.hoverghini.save.vaultCash),150);
  await page.evaluate(()=>window.hoverghini.openModal('couch'));
  page.on('dialog',d=>d.accept());
  await page.locator('[data-act=random-couch]').click();
  await page.waitForFunction(()=>!window.hoverghini.loading&&window.hoverghini.save.vaultCash===0);
  assert.ok(await page.evaluate(()=>!!window.hoverghini.save.safehouse));
  assert.deepEqual(errors,[]);console.log('Couch search, exact saved coordinates, travel, reload, return, stash and random new game passed.');
 }finally{if(browser)await browser.close();server.kill()}
})().catch(e=>{console.error(e);process.exitCode=1});
